// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6ZjBpP1WdInc4MYoh-k6HV5asS-BNR4',
    appId: '1:787349299655:web:a5630ca4921cb8402bf9e2',
    messagingSenderId: '787349299655',
    projectId: 'heart-connect-e2d17',
    authDomain: 'heart-connect-e2d17.firebaseapp.com',
    storageBucket: 'heart-connect-e2d17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2SXJH-8-2kfb7TbjIQEc68qo0sxLI8TI',
    appId: '1:787349299655:android:b909db20d254a21c2bf9e2',
    messagingSenderId: '787349299655',
    projectId: 'heart-connect-e2d17',
    storageBucket: 'heart-connect-e2d17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhgAIrmcrQLG0-SBn6FBoVjh_OfPvULJU',
    appId: '1:787349299655:ios:cdffbf2fe65f17cd2bf9e2',
    messagingSenderId: '787349299655',
    projectId: 'heart-connect-e2d17',
    storageBucket: 'heart-connect-e2d17.firebasestorage.app',
    iosBundleId: 'com.example.heartConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhgAIrmcrQLG0-SBn6FBoVjh_OfPvULJU',
    appId: '1:787349299655:ios:cdffbf2fe65f17cd2bf9e2',
    messagingSenderId: '787349299655',
    projectId: 'heart-connect-e2d17',
    storageBucket: 'heart-connect-e2d17.firebasestorage.app',
    iosBundleId: 'com.example.heartConnectApp',
  );
}
